const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={file:null,img:null,url:null,mode:"lossless",format:"image/webp",quality:.85,output:null};
function bytes(n){if(!n)return"—";let u=["B","KB","MB","MB"],i=0;while(n>=1024&&i<3){n/=1024;i++}return`${n.toFixed(n<10?2:1)} ${u[i]}`}
function percent(a,b){if(!a)return"0%";return Math.max(0,(1-b/a)*100).toFixed(1)+"%"}
function load(file){if(!file||!file.type.startsWith("image/"))return;S.file=file;if(S.url)URL.revokeObjectURL(S.url);S.url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{S.img=img;$("#before").src=S.url;$("#beforeSize").textContent=bytes(file.size);$("#statBefore").textContent=bytes(file.size);$("#beforeMeta").textContent=`${img.naturalWidth} × ${img.naturalHeight} • ${file.type.split("/")[1].toUpperCase()}`;$("#dimensions").textContent=`${img.naturalWidth} × ${img.naturalHeight}`;$("#dot").classList.add("ready");$("#status").textContent="تصویر آماده فشرده‌سازی است";compress()};img.src=S.url}
$("#file").onchange=e=>load(e.target.files[0]);["dragenter","dragover"].forEach(x=>$("#drop").addEventListener(x,e=>{e.preventDefault();$("#drop").classList.add("drag")}));["dragleave","drop"].forEach(x=>$("#drop").addEventListener(x,e=>{e.preventDefault();$("#drop").classList.remove("drag")}));$("#drop").addEventListener("drop",e=>load(e.dataTransfer.files[0]));
$$(".modes button").forEach(b=>b.onclick=()=>{$$(".modes button").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.mode=b.dataset.mode;if(S.mode==="lossless"){S.format="image/png";$("#quality").value=100}else if(S.mode==="high"){S.format="image/jpeg";$("#quality").value=60}else{S.format="image/webp";$("#quality").value=85}updateFormatUI();$("#qualityText").textContent=$("#quality").value+"%";compress()});
$$(".formats button").forEach(b=>b.onclick=()=>{S.format=b.dataset.format;$$(".formats button").forEach(x=>x.classList.toggle("active",x===b));compress()});
function updateFormatUI(){$$(".formats button").forEach(b=>b.classList.toggle("active",b.dataset.format===S.format));$("#outFormat").textContent=S.format.split("/")[1].toUpperCase()}
$("#quality").oninput=e=>{S.quality=+e.target.value/100;$("#qualityText").textContent=e.target.value+"%";compress()};
$("#compress").onclick=compress;
function compress(){if(!S.img||!S.file)return;let c=document.createElement("canvas");c.width=S.img.naturalWidth;c.height=S.img.naturalHeight;let x=c.getContext("2d");x.drawImage(S.img,0,0);
let q=S.quality;if(S.mode==="lossless")q=1;
c.toBlob(blob=>{if(!blob)return;S.output=blob;let u=URL.createObjectURL(blob);$("#after").src=u;$("#afterSize").textContent=bytes(blob.size);$("#statAfter").textContent=bytes(blob.size);$("#saving").textContent=percent(S.file.size,blob.size);$("#afterMeta").textContent=`${c.width} × ${c.height} • ${S.format.split("/")[1].toUpperCase()}`;updateFormatUI();},S.format,q)}
$("#download").onclick=()=>{if(!S.output)return alert("ابتدا یک تصویر انتخاب و فشرده‌سازی کنید.");let ext=S.format==="image/jpeg"?"jpg":S.format==="image/png"?"png":"webp",a=document.createElement("a");a.href=URL.createObjectURL(S.output);a.download=`compressed-image.${ext}`;a.click()};
